### ISSUE TITLE
Suggestion: Use OWO Registry to better optimize registrering of blocks

### ISSUE THREAD

**Issue by Dragon-Seeker** [matthewperiut/Chisel-Reborn#10]
Could be easier to implement OWO's registry system for the blocks as it seems that such would remove the need for the registry method call as it basically goes thru each field of blocks and allows for custom code to be ran with registry and allow for any block to be registered without the need to also create a Reg() method call.

Example: https://docs.wispforest.io/owo/registration/

**Comment by matthewperiut** [comment]
Woah, I've seen owo-lib around other mods but its features do seem pretty cool. I'll take a look into incorporating it

**Comment by matthewperiut** [comment]
I'm worried about adding another dependency so I'm not going to go through with it, but I have thought about it.
