### ISSUE TITLE
Mod Support

### ISSUE THREAD

**Issue by ardissaps** [matthewperiut/Chisel-Reborn#13]
Would you like to support mod that already have variation to be able to use the tool from you? like [Blockus](https://www.curseforge.com/minecraft/mc-mods/blockus). I mean no need to add new block to support that mod, just make your tool be able to craft them for consistency. Thanks! Would also be convenience to be able to chisel placed block with right click.

**Comment by matthewperiut** [comment]
the external mods can add support using the api exposed by this mod.
