### ISSUE TITLE
[1.18.2] plans to port Laboratory blocks and many other missing blocks from the original Chisel Mod?

### ISSUE THREAD

**Issue by MSandro** [matthewperiut/Chisel-Reborn#16]
hope the title describes enoght :)

thanks for your great work 👍

**Comment by matthewperiut** [comment]
Many of these blocks are super complex and I'd have to port the original connected blocks mod, where I'm instead using alternatives such as athena or continuity. You can 100% make them in a seperate add-on mod but I do not plan to support them myself.
