### ISSUE TITLE
Some connected wooden textures acting weird

### ISSUE THREAD

**Issue by Nighthawk558** [matthewperiut/Chisel-Reborn#18]
I have a problem where it seems like the connected textures for large wooden planks of any sort are half-changed with the textures for large encased wooden planks

![2022-09-25_09 43 52](https://user-images.githubusercontent.com/114331851/192133626-4bc07ec8-869d-46c7-a7ff-b0f490f55caa.png)

![2022-09-25_09 43 57](https://user-images.githubusercontent.com/114331851/192133672-7fea422d-0166-46ca-838e-5286db93ffa1.png)

This is also the case for smooth planks

![2022-09-25_09 55 49](https://user-images.githubusercontent.com/114331851/192134008-e3728412-d60b-4fbf-83b6-2f2a37a865ff.png)

![2022-09-25_09 56 07](https://user-images.githubusercontent.com/114331851/192134020-af1d54fe-0e5d-45b6-9847-792af5b59994.png)

Only mods I have installed are, Fabric API (version 0.61.0+1.19.2), Fabricated Chisel (version 1.4.6+1.19), and Continuity (version 2.0.1+1.19). Aswell as the Fabric launcher (version 0.14.9) and I use MultiMC as my launcher for Minecraft

**Comment by Nighthawk558** [comment]
I first encountered this issue on a survival world with a bunch more mods, but it still occurred in a separated instance with only those three mods

**Comment by matthewperiut** [comment]
unfortunately due to the CTM mods available, i can't fix this. If Athena supports full fat CTM let me know.
