### ISSUE TITLE
Suggestion: More space blocks?

### ISSUE THREAD

**Issue by Mollykate20** [matthewperiut/Chisel-Reborn#20]
Hi! I really love the space blocks for the Iron, Gold, and Diamond but I noticed there was a lack of just "void of Space" type blocks. I love the purple hued ones a lot and can't find anything to match it. Could you perhaps add a blank one with something? Maybe obsidian or amethyst?

**Comment by Mollykate20** [comment]
Or Coal!

**Comment by matthewperiut** [comment]
If you would like to add blocks, feel free to PR! It's not that complicated. Honestly, I'm not much of an artist, but if you drop pngs in some dropbox, I'd be happy to make an effort to add them.
