### ISSUE TITLE
Modrinth does not contain updated version of mod which fixes crash

### ISSUE THREAD

**Issue by mounderfod** [matthewperiut/Chisel-Reborn#21]
Version 1.4.7 fixes a crash with Factory Blocks (matthewperiut/factory_blocks/issues/2) but Modrinth has only up to 1.4.6

![image](https://user-images.githubusercontent.com/24373708/219198095-ec361992-0aff-4f1e-99ce-1283f80bf7c2.png)

**Comment by JackDainzh** [comment]
Update to 1.4.7 ver. of Chisel and 1.0.1 ver. of factory blocks. from Curseforge.

**Comment by mounderfod** [comment]
Is there any reason why these updates are not available on Modrinth?

**Comment by matthewperiut** [comment]
1.4.7 is present for 1.19.2 now
