### ISSUE TITLE
Hitting stairs with the chisel tool deletes the stairs

### ISSUE THREAD

**Issue by MoonliteDelight** [matthewperiut/Chisel-Reborn#23]
Basically what the title says. If you hit stairs with the chisel tool, it just... deletes them. There's no ghost block, no dropped block, and there's nothing left in its place. It seems to happen to every stair, not just wooden/brick/etc. ones.

I've attached my game's logs, but there was no entry for the deleted stair events. This is moreso for the list of mods I'm running. 

[latest.log](https://github.com/matthewperiut/Chisel-Reborn/files/10945400/latest.log)

**Comment by matthewperiut** [comment]
I'm not going to lie, I doubted you and audibly gasped when I did it and it just disappeared. will fix

**Comment by matthewperiut** [comment]
thank you
