### ISSUE TITLE
Chiseled purpur blocks unobtainable

### ISSUE THREAD

**Issue by redcatone** [matthewperiut/Chisel-Reborn#28]
None of the chiseled purpur variants are unobtainable since the `minecraft:purpur_block` does not chisel into the chisel variants, only the default minecraft stair, slab, and pillar.

```
Fabric Loader 0.14.22

architectury-6.5.85-fabric
chisel-1.4.7+1.19.2
cloth-config-8.3.103-fabric
fabric-api-0.76.1+1.19.2
RoughlyEnoughItems-9.1.643
```

**Comment by Nitjsefnie** [comment]
I just came across this, this is still an issue, bump

**Comment by matthewperiut** [comment]
whoops this went under the radar
