### ISSUE TITLE
Stone issues

### ISSUE THREAD

**Issue by DemonSlayer112** [matthewperiut/Chisel-Reborn#29]
This is a great mod but it has a slightly overpowered oversight.
It counts blocks made by cobbled deepslate, such as, Polished Deepslate, Deepslate Bricks etc for just normal Deepslate category.

Which to me is bad.
Just lets you turn cobbled deepslate to polished then mod magically turns it into deepslate.
Should have these in their own group with cobbled deepslate,

**Comment by matthewperiut** [comment]
Intended, I personally enjoy this aspect of it.
