### ISSUE TITLE
Extra Jars - Breaking mod "MultiBeds"

### ISSUE THREAD

**Issue by A00826925** [matthewperiut/Chisel-Reborn#30]
I have a concern on how this mod has to create Jars for "Continuity, Chisel, and Templates. Under normal forge conditions these should (probably) not load (if made for fabric ?), but bundling with Sinytra Connector and Forgified fabric API might be breaking models from the mod MultiBeds, i wont do further testing without connector and forgified fabric api, but i found out this mod was the issue in my current setup.

**Comment by matthewperiut** [comment]
Should be fixed in 1.7.0
