### ISSUE TITLE
(Forge) A version that doesn't install Templates 

### ISSUE THREAD

**Issue by RedCraft86** [matthewperiut/Chisel-Reborn#31]
As the title suggests, I think some of us or at least I would appreciate a version of the mod that doesn't have the Templates mod included. On forge, there's already a mod called Framed Blocks and I'd rather use that since Templates seem to have some rendering issues when being used with connector.

**Comment by twilight-sparkle-irl** [comment]
It kind of looks like you can just accomplish this by installing Sinytra Connector, Forgified Fabric API, Connector Extras, and then Continuity and the fabric version of this mod.
