### ISSUE TITLE
Chisel-Reborn Forge Unusable

### ISSUE THREAD

**Issue by litjohn50** [matthewperiut/Chisel-Reborn#32]
With the requirement to use Continuity and Connector for forge.

Rendering is buggered. 

Continuity refuses to support Connector. 

https://github.com/PepperCode1/Continuity/issues/324

Is there a way to port to forge without the need for continuity?

**Comment by Su5eD** [comment]
This should be solved on Connector's side, as it has nothing to do with the mod
