### ISSUE TITLE
Game Crashes when opening the chisel menu on multiplayer.

### ISSUE THREAD

**Issue by LadyStrella** [matthewperiut/Chisel-Reborn#35]
Works fine on singleplayer, server has the same modlist, right clicking the chisel menu on a server will kick you back to the menu
![image](https://github.com/matthewperiut/Chisel-Reborn/assets/90349569/d580b49c-692b-4d55-86d3-bb5aee7674d6)

**Comment by LadyStrella** [comment]
fabric version, forgot to mention, version 1.7.1 downloaded from modrinth, server shows the same error, cant find anything on the logs that could relate to it.

**Comment by dlabaja** [comment]
same issue here

**Comment by Princik** [comment]
Also same issue here

**Comment by JackHTerrell** [comment]
Same issue, Forge 1.20.1

**Comment by VeneratedLerkur** [comment]
I also caught an exception but looks like mine is slightly different. not sure how much that matters.

Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.world.inventory.Menutype@701e59cb in map registry[ResourceKey[minecraft:root / minecraft:menu](stable)]

**Comment by matthewperiut** [comment]
Thanks everybody for reporting this issue! It's now resolved on 1.7.2 which is on Modrinth and CurseForge now!
Sorry for taking so long, I took a step away from minecraft modding for a little while
