### ISSUE TITLE
Uncraftable Chisel

### ISSUE THREAD

**Issue by RampiYee** [matthewperiut/Chisel-Reborn#37]
Literally what it says in the subject line
(even the recipe doesn't show up)
Version of minecraft 1.20.6
Version of mod [1.20.6] Fabric 1.7.2
![image](https://github.com/matthewperiut/Chisel-Reborn/assets/116636359/a0dd9ad8-eecb-4d9e-ae29-05ae9517d73d)

**Comment by RampiYee** [comment]
[craftable_chisel.zip](https://github.com/user-attachments/files/15613751/craftable_chisel.zip)
I tried for the first time to figure out how datapacks work, and I managed to fix it, it looks like the result of the recipe should now be written with an "id" instead of an "item"
I'll attach this datapack to make it easier for you

**Comment by matthewperiut** [comment]
Oh wow, I just saw this turns out that it had to be changed from recipes/chisel to recipe/chisel. Fixing now thank you for the report!

**Comment by matthewperiut** [comment]
fixed in latest versions
