### ISSUE TITLE
New Feature: AE2 integration or chisel all button.

### ISSUE THREAD

**Issue by VoidTest** [matthewperiut/Chisel-Reborn#46]
The mod has great blocks but it takes forever to get a lot of them so having the ability for ae2 to auto craft it would be great but that might be hard to make so i also suggest adding a chisel all button in the menu that chisels all blocks in your inventory.

**Comment by matthewperiut** [comment]
This seems extensive, I just wanted to add pretty blocks to my game lol. Feel free to make a separate mod to add this or asking someone to, because you can 100% do this with an addon-like mod.
