### ISSUE TITLE
[Fabric 1.20.4] v1.8.0 client crash when using Chisel, "Rendering screen" NoSuchMethod

### ISSUE THREAD

**Issue by BrandonPotts** [matthewperiut/Chisel-Reborn#48]
Client crash upon using the Chisel item with mod version 1.8.0 on Fabric 1.20.4

Tried with a few different Fabric and Fabric API versions, no dice. Crash does not occur after downgrading to Reborn v1.7.2

Crash report: 
[crash-2024-08-15_12.44.18-client.txt](https://github.com/user-attachments/files/16629875/crash-2024-08-15_12.44.18-client.txt)

**Comment by matthewperiut** [comment]
if the older version works, then that's fine, I'm sorry about the crash but I'm not going to roll back to try and fix it for an older version.
