### ISSUE TITLE
Add Tags for Groups of Blocks

### ISSUE THREAD

**Issue by TheBedrockMaster** [matthewperiut/Chisel-Reborn#49]
My suggestion is to add item tags to each group of blocks like andesite for example. The tag for all the andesite variations would be `chisel:andesite` (or something similar). This would make it easier for modpacks to do something with a certain group of blocks. This could also be done for block tags but it wouldn't be as useful.

**Comment by matthewperiut** [comment]
Modpacks can already easily give any block tags, so can mods. I don't find this necessary, but I do appreciate the issue!

**Comment by TheBedrockMaster** [comment]
Fair enough, I'm not adding all those tags though so oh well 🤣
