### ISSUE TITLE
Duping Method ! | Atm 10 | ver 1.8.1

### ISSUE THREAD

**Issue by john13210** [matthewperiut/Chisel-Reborn#51]
Chisel Reborn : ver 1.8.1 for 1.21.1 
Modpack : All The Mods 10 ver 10-0.40
Neoforge : 21.1.28

Tested and was working on server idk about singleplayer

Method:
-Get some items in your inventory and place a inventory like a chest near you
-Leave and rejoin server to save your inventory
-Put the stuff you got for duping
-Get chisel
-Put 1 thing in (for example andesite block)
-Exit from it
-Enter and take the item (from the input slot) with shift left click rly fast
-Then you get kicked from the server with a message :

Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode a packett 'clientbound/minecraft:container_set_content'

when you come back on the server your inventory will revert to the saved state when you were leaving and rejoining the server

**Comment by matthewperiut** [comment]
This is ultimately a minecraft bug, report to mojang, basically there's a desync in the ScreenHandler.
