### ISSUE TITLE
PSA (and important issue): 1.8.1 has wrong version tags on Modrinth

### ISSUE THREAD

**Issue by NoaHimesaka1873** [matthewperiut/Chisel-Reborn#52]
It should be tagged as 1.21.1, but it's tagged for all Minecraft versions. This actually ruined my world. Please check version tags before uploading to prevent disasters like mine from happening again.

**Comment by matthewperiut** [comment]
I apologize, I will make sure to utilize proper tags from this point forward, including loader and version. Thank you, and again I'm sorry for that.
